title: Seungsu Han
subtitle: undergraduated student, Seoul National University
logo: picture/IMG_0869.jpg
#description: phone: +82 10-4234-1413
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
